"""
users.py
User management. Direct port of Users.gs.

Each user's password is auto-generated by the system from their
Role and Branch, never chosen by hand:

    first 3 letters of Role + first 3 letters of Branch + "123"

e.g. Role "Manager",     Branch "KOZHIKODE"   ->  "ManKOZ123"
     Role "HOF",         Branch "TIRUR"       ->  "HOFTIR123"
     Role "Head Office", Branch "HEAD OFFICE" ->  "HeaHEA123"

The plaintext password is only ever shown once, in the response to
users.create / users.resetPassword. Only its SHA-256 hash is stored.

Permission split between Admin and Head Office:
  - Admin can create/edit/delete/reset ANY role, including other
    Admins and Head Office users.
  - Head Office can create/edit/reset-password for SCM, HOF, and
    Manager ONLY. It can never touch an Admin or another Head
    Office account, and it can never delete any account (deletion
    stays Admin-only).
"""
import re
import random
import string
import datetime

import config
from db_utils import read_sheet_as_objects_, append_row_, update_row_fields_, delete_row_
from auth import ApiError, hash_password_, require_role_
from audit_log import log_audit_

# Roles a Head Office user is allowed to create/manage. Deliberately
# excludes ROLE_ADMIN and ROLE_HEAD_OFFICE itself.
HEAD_OFFICE_MANAGEABLE_ROLES = [config.ROLE_SCM, config.ROLE_HOF, config.ROLE_MANAGER]


def generate_password_(role, branch):
    """
    Builds the auto-generated password for a given role + branch.
    Non-letters are stripped before taking the first 3 characters so
    spacing in a branch/role name doesn't shrink the slice.
    """
    role_part = re.sub(r'[^a-zA-Z]', '', str(role or ''))[:3]
    branch_part = re.sub(r'[^a-zA-Z]', '', str(branch or ''))[:3].upper()
    return role_part + branch_part + '123'


def generate_named_password_(name):
    """
    "Magnus" password scheme used by the Create User form's
    "Auto-generate password" checkbox:

        <first name as typed> + M + <2-digit year> + <4 random letters/digits>

    e.g. name "John Doe" created in 2026 -> "JohnM26aB3x"

    The "M" stands for Magnus (the company), "26" is the current
    2-digit year, and the 4-character tail deliberately mixes upper-
    and lower-case letters with digits so the final password is
    meaningfully case-sensitive. A fresh tail is drawn (up to 25
    tries) until the resulting password doesn't collide with any
    existing user's stored password hash, so every generated password
    is guaranteed unique across the whole system.
    """
    first_name = (str(name or '').strip().split(' ') or ['User'])[0] or 'User'
    yy = datetime.date.today().strftime('%y')
    existing_hashes = {u.get('Password') for u in read_sheet_as_objects_(config.SHEET_USERS)}
    alphabet = string.ascii_letters + string.digits

    for _ in range(25):
        tail = ''.join(random.choice(alphabet) for _ in range(4))
        candidate = f"{first_name}M{yy}{tail}"
        if hash_password_(candidate) not in existing_hashes:
            return candidate
    # Astronomically unlikely fallback (would need 25 straight
    # collisions out of 62^4 possibilities) - widen the tail instead
    # of looping forever.
    tail = ''.join(random.choice(alphabet) for _ in range(8))
    return f"{first_name}M{yy}{tail}"


def assert_can_manage_role_(acting_user, target_role):
    """Raises AUTH_FORBIDDEN unless acting_user may manage target_role."""
    if acting_user['role'] == config.ROLE_ADMIN:
        return  # Admin can manage any role
    if acting_user['role'] == config.ROLE_HEAD_OFFICE and target_role in HEAD_OFFICE_MANAGEABLE_ROLES:
        return
    raise ApiError('AUTH_FORBIDDEN')


def create_user_(acting_user, payload):
    if not payload.get('email') or not payload.get('name') or not payload.get('branch') or not payload.get('role'):
        raise ApiError('BAD_REQUEST')
    if payload['role'] not in config.VALID_ROLES:
        raise ApiError('BAD_REQUEST')
    assert_can_manage_role_(acting_user, payload['role'])

    from auth import find_user_by_email_
    existing = find_user_by_email_(payload['email'])
    if existing:
        raise ApiError('BAD_REQUEST')

    branch = 'HEAD OFFICE' if payload['role'] in (config.ROLE_ADMIN, config.ROLE_HEAD_OFFICE) else payload['branch']

    # Three ways this can go:
    #   1. "Auto-generate password" checkbox ticked - use the new
    #      Magnus scheme, ignoring anything typed into the password box.
    #   2. Checkbox unticked and a password was typed - use it as-is
    #      (min 6 characters).
    #   3. Checkbox unticked and nothing was typed - password is now a
    #      required field on the form, so this is a hard error.
    auto_generate = bool(payload.get('autoGenerate'))
    custom_password = str(payload.get('password') or '').strip()

    if auto_generate:
        final_password = generate_named_password_(payload['name'])
        was_auto_generated = True
    elif custom_password:
        if len(custom_password) < 6:
            raise ApiError('PASSWORD_TOO_SHORT')
        final_password = custom_password
        was_auto_generated = False
    else:
        raise ApiError('PASSWORD_REQUIRED')

    append_row_(config.SHEET_USERS, {
        'Email': payload['email'].lower(),
        'Name': payload['name'],
        'Branch': branch,
        'Role': payload['role'],
        'Password': hash_password_(final_password),
    })

    log_audit_(acting_user['email'], 'CREATE',
               f"Created user {payload['email']} ({payload['role']})"
               + (' with an auto-generated password' if was_auto_generated else ' with a custom password'),
               branch, payload.get('browser'))
    # `generatedPassword` is still returned either way - the create-user
    # UI shows/copies it once regardless of whether it was auto-made or
    # typed by the creator, since the creator may not remember exactly
    # what they typed by the time the success screen appears.
    return {'success': True, 'generatedPassword': final_password, 'wasAutoGenerated': was_auto_generated}


def update_user_(acting_user, payload):
    if not payload.get('email'):
        raise ApiError('BAD_REQUEST')
    rows = read_sheet_as_objects_(config.SHEET_USERS)
    match = next((u for u in rows if str(u.get('Email', '')).lower() == payload['email'].lower()), None)
    if not match:
        raise ApiError('BAD_REQUEST')

    # A Head Office user may only touch accounts that are currently
    # SCM/HOF/Manager, and may only move them to another of those roles.
    assert_can_manage_role_(acting_user, match['Role'])
    if payload.get('role'):
        assert_can_manage_role_(acting_user, payload['role'])

    fields = {}
    if payload.get('name'):
        fields['Name'] = payload['name']

    new_role = match['Role']
    if payload.get('role'):
        if payload['role'] not in config.VALID_ROLES:
            raise ApiError('BAD_REQUEST')
        new_role = payload['role']
        fields['Role'] = new_role

    new_branch = match['Branch']
    if new_role in (config.ROLE_ADMIN, config.ROLE_HEAD_OFFICE):
        new_branch = 'HEAD OFFICE'
    elif payload.get('branch'):
        new_branch = payload['branch']
    if new_branch != match['Branch']:
        fields['Branch'] = new_branch

    result = {'success': True}

    # The password is derived from Role + Branch, so if either changed
    # the old password no longer matches the formula - regenerate it.
    role_changed = new_role != match['Role']
    branch_changed = new_branch != match['Branch']
    if role_changed or branch_changed:
        generated_password = generate_password_(new_role, new_branch)
        fields['Password'] = hash_password_(generated_password)
        result['generatedPassword'] = generated_password

    update_row_fields_(config.SHEET_USERS, match['__row'], fields)
    log_audit_(acting_user['email'], 'UPDATE', 'Updated user ' + payload['email'], new_branch, payload.get('browser'))
    return result


def delete_user_(acting_user, email):
    require_role_(acting_user, [config.ROLE_ADMIN])  # deletion is always Admin-only
    if not email:
        raise ApiError('BAD_REQUEST')
    if email.lower() == acting_user['email'].lower():
        raise ApiError('BAD_REQUEST')  # can't delete yourself

    rows = read_sheet_as_objects_(config.SHEET_USERS)
    match = next((u for u in rows if str(u.get('Email', '')).lower() == email.lower()), None)
    if not match:
        raise ApiError('BAD_REQUEST')

    delete_row_(config.SHEET_USERS, match['__row'])
    log_audit_(acting_user['email'], 'DELETE', 'Deleted user ' + email, '', '')
    return {'success': True}


def reset_user_password_(acting_user, email):
    """
    Resets a user's password back to the system-generated default for
    their current Role + Branch. A Head Office user may only do this
    for the SCM/HOF/Manager accounts it's allowed to manage.
    """
    if not email:
        raise ApiError('BAD_REQUEST')
    rows = read_sheet_as_objects_(config.SHEET_USERS)
    match = next((u for u in rows if str(u.get('Email', '')).lower() == email.lower()), None)
    if not match:
        raise ApiError('BAD_REQUEST')

    assert_can_manage_role_(acting_user, match['Role'])

    generated_password = generate_password_(match['Role'], match['Branch'])
    update_row_fields_(config.SHEET_USERS, match['__row'], {'Password': hash_password_(generated_password)})

    log_audit_(acting_user['email'], 'UPDATE', 'Reset password for ' + email, match['Branch'], '')
    return {'success': True, 'generatedPassword': generated_password}